default_language_version:
  python: python3.8
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
      - id: check-symlinks
      - id: check-json
      - id: pretty-format-json
        args: ["--autofix", "--allow-missing-credentials"]
      - id: check-merge-conflict
      - id: check-added-large-files
      - id: check-ast
      - id: check-yaml
      - id: trailing-whitespace
      - id: debug-statements
  - repo: https://gitlab.com/pycqa/flake8
    rev: "3.9.2"
    hooks:
      - id: flake8
        files: '\.py$'
        args:
          - --select=F401,F403,F406,F821
  - repo: https://github.com/humitos/mirrors-autoflake
    rev: v1.1
    hooks:
      - id: autoflake
        files: '\.py$'
        exclude: '^\..*'
        args: ["--in-place", "--remove-all-unused-imports"]
  - repo: https://github.com/psf/black
    rev: 22.3.0
    hooks:
      - id: black
        args: ["--target-version", "py37"]