# Generated by Django 3.2.11 on 2022-06-27 13:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="payment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "payment_id",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                (
                    "method",
                    models.CharField(
                        choices=[("paypal", "paypal"), ("stripe", "stripe")],
                        max_length=20,
                        verbose_name="Method payment",
                    ),
                ),
                ("amount_paid", models.CharField(max_length=100)),
                (
                    "status",
                    models.CharField(
                        choices=[("paypal", "paypal"), ("stripe", "stripe")],
                        max_length=20,
                        verbose_name="Method payment",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_payment",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
