# Generated by Django 3.2.11 on 2022-06-30 22:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("menu", "0002_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="category",
            options={"verbose_name": "category", "verbose_name_plural": "categories"},
        ),
        migrations.AlterModelOptions(
            name="foodgallery",
            options={
                "verbose_name": "food gallery",
                "verbose_name_plural": "food galleries",
            },
        ),
        migrations.AlterModelOptions(
            name="reviewrating",
            options={
                "verbose_name": "review rating",
                "verbose_name_plural": "reviews rating",
            },
        ),
    ]
