# Generated by Django 3.2.11 on 2022-06-28 11:56

from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("menu", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "pkid",
                    models.BigAutoField(
                        editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "id",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "order_number",
                    models.CharField(max_length=20, verbose_name="order number"),
                ),
                ("address", models.CharField(max_length=100, verbose_name="address")),
                (
                    "country",
                    django_countries.fields.CountryField(
                        max_length=100, verbose_name="country"
                    ),
                ),
                ("city", models.CharField(max_length=100, verbose_name="city")),
                (
                    "order_note",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="order note"
                    ),
                ),
                (
                    "order_total",
                    models.FloatField(max_length=100, verbose_name="order total"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("new", "new"),
                            ("accepted", "accepted"),
                            ("completed,", "completed,"),
                            ("cancled", "cancled"),
                        ],
                        default="new",
                        max_length=10,
                        verbose_name="status",
                    ),
                ),
                (
                    "is_ordered",
                    models.BooleanField(default=False, verbose_name="is ordered"),
                ),
            ],
            options={
                "ordering": ["-created_at", "-updated_at"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="OrderItem",
            fields=[
                (
                    "pkid",
                    models.BigAutoField(
                        editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "id",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("quantity", models.IntegerField(default=1, verbose_name="quantity")),
                ("food_price", models.FloatField(verbose_name="food price")),
                ("ordered", models.BooleanField(default=False, verbose_name="ordered")),
                (
                    "food",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="food_orderitems",
                        to="menu.food",
                        verbose_name="food",
                    ),
                ),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="order_orderitems",
                        to="orders.order",
                        verbose_name="order",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at", "-updated_at"],
                "abstract": False,
            },
        ),
    ]
