# Generated by Django 3.2.11 on 2022-06-24 11:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "pkid",
                    models.BigAutoField(
                        editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "id",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "order_number",
                    models.CharField(max_length=20, verbose_name="order number"),
                ),
                ("address", models.CharField(max_length=50, verbose_name="address")),
                (
                    "country",
                    django_countries.fields.CountryField(
                        max_length=50, verbose_name="country"
                    ),
                ),
                ("city", models.CharField(max_length=50, verbose_name="city")),
                (
                    "order_note",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="order note"
                    ),
                ),
                ("order_total", models.FloatField(verbose_name="order total")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("new", "new"),
                            ("accepted", "accepted"),
                            ("completed,", "completed,"),
                            ("cancled", "cancled"),
                        ],
                        default="New",
                        max_length=10,
                        verbose_name="order total",
                    ),
                ),
                (
                    "is_ordered",
                    models.BooleanField(default=False, verbose_name="is order"),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="order",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="user",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at", "-updated_at"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="OrderItem",
            fields=[
                (
                    "pkid",
                    models.BigAutoField(
                        editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "id",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("quantity", models.IntegerField(verbose_name="quantity")),
                ("food_price", models.FloatField(verbose_name="food price")),
                ("ordered", models.BooleanField(default=False, verbose_name="ordered")),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="orders.order",
                        verbose_name="order",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="order_item",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at", "-updated_at"],
                "abstract": False,
            },
        ),
    ]
