# Generated by Django 3.2.11 on 2022-06-24 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="is_ordered",
            field=models.BooleanField(default=False, verbose_name="is ordered"),
        ),
        migrations.AlterField(
            model_name="order",
            name="status",
            field=models.CharField(
                choices=[
                    ("new", "new"),
                    ("accepted", "accepted"),
                    ("completed,", "completed,"),
                    ("cancled", "cancled"),
                ],
                default="New",
                max_length=10,
                verbose_name="status",
            ),
        ),
    ]
