# Generated by Django 3.2.11 on 2022-06-27 20:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0003_alter_payment_status"),
        ("orders", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="payment",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="payment_order",
                to="payments.payment",
                verbose_name="payment",
            ),
        ),
        migrations.AddField(
            model_name="orderitem",
            name="payment",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="payment_orderitem",
                to="payments.payment",
                verbose_name="payment",
            ),
        ),
    ]
