# Generated by Django 3.2.11 on 2022-06-30 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0003_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="order_total",
            field=models.FloatField(
                blank=True, max_length=100, null=True, verbose_name="order total"
            ),
        ),
    ]
