# Generated by Django 3.2.11 on 2022-06-24 15:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0003_alter_order_status"),
    ]

    operations = [
        migrations.CreateModel(
            name="AcceptedOrder",
            fields=[],
            options={
                "verbose_name": "Order accepted",
                "verbose_name_plural": "Orders accepted",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("orders.order",),
        ),
    ]
