# Generated by Django 3.2.11 on 2022-06-24 19:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0004_acceptedorder"),
    ]

    operations = [
        migrations.CreateModel(
            name="CancledOrder",
            fields=[],
            options={
                "verbose_name": "Order cancled",
                "verbose_name_plural": "Orders cancled",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("orders.order",),
        ),
        migrations.CreateModel(
            name="CompletedOrder",
            fields=[],
            options={
                "verbose_name": "Order completed",
                "verbose_name_plural": "Orders completed",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("orders.order",),
        ),
    ]
