# Generated by Django 3.2.11 on 2022-06-30 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0005_alter_order_order_number"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="order_number",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="order number"
            ),
        ),
    ]
