# Generated by Django 3.2.11 on 2022-07-04 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0006_alter_order_order_number"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="status",
            field=models.CharField(
                choices=[
                    ("new", "new"),
                    ("accepted", "accepted"),
                    ("completed", "completed,"),
                    ("cancled", "cancled"),
                ],
                default="new",
                max_length=10,
                verbose_name="status",
            ),
        ),
    ]
