# Generated by Django 3.2.11 on 2022-07-09 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="profile_photo",
            field=models.ImageField(
                blank=True,
                upload_to="photos/profile_photo",
                verbose_name="profile photo",
            ),
        ),
    ]
